#!/usr/bin/env php
<?php

use Maslosoft\Themes\Application\ConsoleApplication;

date_default_timezone_set('UTC');

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require_once(__DIR__.'/vendor/autoload.php');
} elseif (file_exists(__DIR__.'/../../autoload.php')) {
    require_once __DIR__ . '/../../autoload.php';
}
$app = new ConsoleApplication();
$app->run();
